apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod-paceme
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hello@leejohnmartin.co.uk
    privateKeySecretRef:
      name: account-key-prod
    solvers: 
      - http01:
          ingress:
            class: traefik
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: selfsigned
# spec:
#   selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paceme-le-certificate
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ required "hostname is required" .Values.hostname }}
  secretName: paceme-le-certificate
  issuerRef:
    name: letsencrypt-prod-paceme
    kind: Issuer