---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  name: traefik-paceme-api
  namespace: {{ required "metadata.namespace is required" .Release.Namespace }}
spec:
  routes:
    - match: Host(`{{ required "hostname is required" .Values.hostname }}`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: paceme-traefik-forward
        - name: api-stripprefix
      services:
        - name: paceme-api
          port: 8081
  tls:
    secretName: paceme-le-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: api-stripprefix
  namespace: {{ required "metadata.namespace is required" .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  name: traefik-paceme-webapp
  namespace: {{ required "metadata.namespace is required" .Release.Namespace }}
spec:
  routes:
    - match: Host(`{{ required "hostname is required" .Values.hostname }}`)
      kind: Rule
      middlewares:
        - name: paceme-traefik-forward
      services:
        - name: paceme-webapp
          port: 9000
  tls:
    secretName: paceme-le-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: paceme-traefik-forward
  namespace: {{ required "metadata.namespace is required" .Release.Namespace }}
spec:
  forwardAuth:
    address: http://paceme-oauth2-proxy.{{ required "metadata.namespace is required" .Release.Namespace }}.svc:4181
    authResponseHeaders:
      - X-Forwarded-User
---
# Source: oauth2-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: paceme-oauth2-proxy
  name: paceme-oauth2-proxy
  namespace: {{ required "metadata.namespace is required" .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4181
    protocol: TCP
    targetPort: 4181
  selector:
    app: paceme-traefik-forward-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paceme-traefik-forward-auth
  labels:
    app: paceme-traefik-forward-auth
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paceme-traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paceme-traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2-arm64
        name: paceme-traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        # - name: DOMAIN
        #   value: {{ .Values.hostname }}
        - name: URL_PATH
          value: /oauth2/callback
        # INSECURE_COOKIE is required unless using https entrypoint
        # - name: INSECURE_COOKIE
        #   value: "true"
        - name: DEFAULT_PROVIDER
          value: generic-oauth
        - name: SECRET
          value: {{ required "oauth2.cookiesecret is required" .Values.oauth2.cookiesecret }}
        - name: PROVIDERS_GENERIC_OAUTH_CLIENT_ID
          value: {{ required "oauth2.clientid is required" .Values.oauth2.clientid  }}
        - name: PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET
          value: {{ required "oauth2.secret is required" .Values.oauth2.secret }}
        - name: PROVIDERS_GENERIC_OAUTH_USER_URL
          value: {{ required "oauth2.userurl is required" .Values.oauth2.userurl }}
        - name: PROVIDERS_GENERIC_OAUTH_AUTH_URL
          value: {{ required "oauth2.authurl is required" .Values.oauth2.authurl }}
        - name: PROVIDERS_GENERIC_OAUTH_TOKEN_URL
          value: {{ required "oauth2.tokenurl is required" .Values.oauth2.tokenurl }}
