apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paceme-webapp
  namespace: {{ .Values.metadata.namespace }}
  name: paceme-webapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: paceme-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: paceme-webapp
      namespace: {{ .Values.metadata.namespace }}
      name: paceme-webapp
    spec:
      containers:
        - name: paceme-webapp
          image: {{ required "webapp.image is required" .Values.webapp.image }}:{{  required "webapp.tag is required" .Values.webapp.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 80
