apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paceme-webapp
  namespace: {{ .Release.Namespace }}
  name: paceme-webapp
spec:
  replicas: {{ required "webapp.replicas is required" .Values.webapp.replicas }}
  selector:
    matchLabels:
      app: paceme-webapp
  template:
    metadata:
      labels:
        app: paceme-webapp
      namespace: {{ .Release.Namespace }}
      name: paceme-webapp
    spec:
      containers:
        - name: paceme-webapp
          image: {{ required "webapp.image is required" .Values.webapp.image }}:{{  required "webapp.tag is required" .Values.webapp.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          volumeMounts:
            - name: webappconfig
              mountPath: /etc/nginx/conf.d/{{ required "hostname is required" .Values.hostname }}.conf
              subPath: nginx_webapp.conf
              readOnly: true    
      volumes: 
        - name: webappconfig
          configMap: 
            name:  paceme-webapp
            defaultMode: 0444
