apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paceme-webapp
  namespace: {{ .Values.metadata.namespace }}
  name: paceme-webapp
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: paceme-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: paceme-webapp
      namespace: {{ .Values.metadata.namespace }}
      name: paceme-webapp
    spec:
      containers:
        - name: paceme-webapp
          image: {{ required "webapp.image is required" .Values.webapp.image }}:{{  required "webapp.tag is required" .Values.webapp.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          volumeMounts:
            - name: webappconfig
              mountPath: /etc/nginx/conf.d/{{ required "hostname is required" .Values.hostname }}.conf
              subPath: nginx_webapp.conf
              readOnly: true    
      volumes: 
        - name: webappconfig
          configMap: 
            name:  paceme-webapp
            defaultMode: 0444
