apiVersion: v1
kind: Service
metadata:
  name: paceme-webapp
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: paceme-webapp
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    app: paceme-webapp
  type: ClusterIP