apiVersion: v1
kind: Service
metadata:
  name: paceme-webapp
  namespace: {{ .Release.Namespace }}
  labels:
    app: paceme-webapp
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 8080
  selector:
    app: paceme-webapp
  type: ClusterIP