AWSTemplateFormatVersion: 2010-09-09
Description: >-
  paceme-api

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 180
    MemorySize: 128
    Environment:
      Variables:
        TRAINING_PLAN_TABLE: !Ref TrainingPlanTable
        TRAINING_PLAN_ACTIVITY_TABLE: !Ref TrainingPlanActivityTable
    Tags: { Key: Project, Value: PaceMeApp }

Resources:

  PaceMeUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: PaceMeUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  PaceMeUserPoolWebAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - phone
        - email
        - profile
        - openid
        - aws.cognito.signin.user.admin
      ExplicitAuthFlows: 
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      UserPoolId: !Ref PaceMeUserPool
      ClientName: PaceMeUserPoolWebAppClient
      GenerateSecret: false
      CallbackURLs:
        - http://localhost:3000/
        - https://app.paceme.info/

  PaceMeUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: pacemewebapp
      UserPoolId: !Ref PaceMeUserPool

  PaceMeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET, PUT, DELETE, OPTIONS'"
        AllowHeaders: "'Access-Control-Allow-Headers', 'Origin'"
        AllowOrigin: "'localhost:3000', 'app.paceme.info'"
        MaxAge: "'600'"
        AllowCredentials: true
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false 
        DefaultAuthorizer: PaceMeCognitoAuthorizer
        Authorizers:
          PaceMeCognitoAuthorizer:
            UserPoolArn: !GetAtt PaceMeUserPool.Arn

  #TODO: Look into this, maybe not creating a million handlers...           
  #https://aws.amazon.com/blogs/aws/api-gateway-update-new-features-simplify-api-development/
  getAllTrainingPlans:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanHandlers.planGetAll
      Description: Get all training plans for logged in user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans
            Method: GET

  createNewPlan:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanHandlers.planCreate
      Description: Create training plan for user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans
            Method: POST

  getTrainingPlan:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanHandlers.planGet
      Description: Get training plan for logged in user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}
            Method: GET

  updateTrainingPlan:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanHandlers.planUpdate
      Description: Update training plan for logged in user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}
            Method: PUT

  deleteTrainingPlan:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanHandlers.planDelete
      Description: Delete training plan for logged in user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}
            Method: DELETE


  getAllTrainingActivities:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanActivityHandlers.activityGetAll
      Description: Get all training plans for logged in user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanActivityTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}/activities
            Method: GET

  createNewActivity:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanActivityHandlers.activityCreate
      Description: Create training plan for user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanActivityTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}/activities
            Method: POST

  getTrainingPlanActivity:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanActivityHandlers.activityGet
      Description: Get training plan activity for logged in user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanActivityTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}/activities/{activityId}
            Method: GET

  updateTrainingPlanActivity:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanActivityHandlers.activityUpdate
      Description: Update training plan activity for logged in user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanActivityTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}/activities/{activityId}
            Method: PUT

  deleteTrainingPlanActivity:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/trainingPlanActivityHandlers.activityDelete
      Description: Delete training plan activity for logged in user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TrainingPlanActivityTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}/activities/{activityId}
            Method: DELETE

  optionsHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/optionHandler.handler
      Description: Get Options
      Events:
        TrainingPlanId:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}
            Method: OPTIONS
        TrainingPlanList:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans
            Method: OPTIONS
        TrainingPlanActivityId:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}/activities/{activityId}
            Method: OPTIONS
        TrainingPlanActivityList:
          Type: Api
          Properties:
            RestApiId: !Ref PaceMeApi
            Path: /trainingplans/{trainingPlanId}/activities
            Method: OPTIONS
  
  TrainingPlanTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
  TrainingPlanActivityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
      - AttributeName: trainingPlanId
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: trainingPlanId
          AttributeType: S

Outputs:
  FunctionApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${PaceMeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UserPoolId:
    Description: "Cognito UserPool Id"
    Value: !Ref PaceMeUserPool
  UserPoolWebClientId:
    Description: "Cognito UserPool Web Client Id"
    Value: !Ref PaceMeUserPoolWebAppClient
