apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.metadata.namespace }}
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: pgrs
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.metadata.namespace }}
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: pgrs
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: paceme
            - name: POSTGRES_USER
              value: paceme
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paceme-api-secrets
                  key: postgrespw
      terminationGracePeriodSeconds: 60
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
