apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-map
  namespace: {{ .Values.metadata.namespace }}
data:
  redis-config: |
    maxmemory 50mb
    maxmemory-policy allkeys-lru    
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Values.metadata.namespace }}
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    infra: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    infra: redis
  namespace: {{ .Values.metadata.namespace }}
  name: paceme-api-redis
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      infra: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        infra: redis
      namespace: {{ .Values.metadata.namespace }}
      name: paceme-api-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.6
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-config-map
            items:
            - key: redis-config
              path: redis.conf