apiVersion: v1
kind: Secret
metadata:
  name: paceme-api-secrets
  namespace: {{ .Values.metadata.namespace }}
type: Opaque
data:
  fitbit-client-id: {{ required "fitbit.clientId is required" .Values.fitbit.clientId | b64enc }}
  fitbit-client-secret: {{ required "fitbit.clientSecret is required" .Values.fitbit.clientSecret | b64enc }}
  postgrespw: {{ required "api.postgrespw is required" .Values.api.postgrespw | b64enc }}
  postgresconnectionstring: {{ required "api.postgresconnectionstring is required" .Values.api.postgresconnectionstring | b64enc }}
