apiVersion: v1
kind: Service
metadata:
  name: paceme-api
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: paceme-api
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: paceme-api
  type: ClusterIP