api:
  image: leemartin77/paceme-api
  tag: latest
  mongo:
    pvName: paceme-api-mongo-storage
webapp: 
  image: leemartin77/paceme-webapp
  tag: latest

hostname: app.paceme.info

ingress:
  enabled: true

metadata: 
  namespace: paceme

autosecretjob: true
nodeEnv: production