apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.metadata.labels.app }}
  namespace: {{ .Values.metadata.namespace }}
  name: paceme-api
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: paceme-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
      namespace: {{ .Values.metadata.namespace }}
      name: paceme-api
    spec:
      containers:
        - name: paceme-api
          image: {{ required "ECRApiRepository is required" .Values.ECRApiRepository }}:{{  required "Image tag is required" .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: AWS_REGION
              value: eu-west-2
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: paceme-api-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: paceme-api-secrets
                  key: aws-secret-access-key
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: paceme-api-secrets
                  key: cognito-user-pool-id
            - name: FITBIT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: paceme-api-secrets
                  key: fitbit-client-id
            - name: FITBIT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paceme-api-secrets
                  key: fitbit-client-secret
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_HOST
              value: redis-service.paceme-api.svc.cluster.local
            - name: USER_SERVICE_TOKEN_TABLE
              value: {{ required "Dynamo.UserServiceToken is required" .Values.Dynamo.UserServiceToken }}
            - name: USER_SETTING_TABLE
              value: {{ required "Dynamo.UserSetting is required" .Values.Dynamo.UserSetting }}
            - name: TRAINING_PLAN_TABLE
              value: {{ required "Dynamo.TrainingPlan is required" .Values.Dynamo.TrainingPlan }}
            - name: TRAINING_PLAN_ACTIVITY_TABLE
              value: {{ required "Dynamo.TrainingPlanActivity is required" .Values.Dynamo.TrainingPlanActivity }}
            - name: NODE_ENV
              value: {{ required "nodeEnv is required" .Values.nodeEnv }}
      imagePullSecrets:
          - name: awsregcred
