apiVersion: v1
kind: Secret
metadata:
  name: paceme-api-secrets
  namespace: {{ .Values.metadata.namespace }}
type: Opaque
data:
  aws-access-key-id: {{ required "Aws.AccessKey is required" .Values.Aws.AccessKey | b64enc }}
  aws-secret-access-key: {{ required "Aws.SecretKey is required" .Values.Aws.SecretKey | b64enc }}
  cognito-user-pool-id: {{ required "CognitoPoolId is required" .Values.CognitoPoolId | b64enc }}
  fitbit-client-id: {{ required "fitbit.clientId is required" .Values.fitbit.clientId | b64enc }}
  fitbit-client-secret: {{ required "fitbit.clientSecret is required" .Values.fitbit.clientSecret | b64enc }}