name: Update AWS Resources
on:
  push:
    branches: 
      - main
    paths:
      - '.github/workflows/build_and_deploy_cdk_main.yml'
      - '.infrastructure/**'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-2
  AWS_DEFAULT_REGION: eu-west-2
  CDK_ENVIRONMENT: Production
jobs:
  build_frontend:
    name: Build CDK/AWS Resources
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: checkout
        uses: actions/checkout@v2
      # Get Node
      - name: get node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      # Get Credstash
      - name: get credstash
        uses: robertbeal/credstash@v8
      # install infrastructure
      - uses: actions/cache@v2
        id: cdk-install
        with:
          path: ./.infrastructure/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./.infrastructure/package.json') }}-${{ hashFiles('./.infrastructure/package-lock.json') }}
      - name: install cdk
        if: steps.cdk-install.outputs.cache-hit != 'true'
        working-directory: ./.infrastructure
        run: npm ci
      # deploy cdk
      - name: deploy cdk
        working-directory: ./.infrastructure
        run: npm run cdk:deploy:out
      # save credstash
      - name: save credstash values
        working-directory: ./.infrastructure
        run: npm run script:outfiletocredstash